language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pandas requests
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - pip install -e .


script:
  - pytest -v --cov=reporec reporec/tests/

notifications:
    email: false

after_success:
  - codecov
